### ISSUE TITLE
Implement weather ingress

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/DTBase#107]
As an example of how data ingress works, and also because many deployments will need it.

**Comment by EdwinB12** [comment]
@mhauru -  Was this implemented in CROP? If so, could you point where exactly its implemented?

**Comment by mhauru** [comment]
That's in here: https://github.com/alan-turing-institute/CROP/blob/main/core/ingress_weather.py
The configuration to run it as an Azure function is here: https://github.com/alan-turing-institute/CROP/tree/main/ingress_functions/weather_func

**Comment by mhauru** [comment]
With Edwin, we've decided to implement a base ingress class, that every instance of an ingress function should subclass. The base class handles things like figuring out talking to the backend API with authentication. From the user's point of view, writing an ingress function looks something like this:

```
class MyIngress(BaseIngress):

    def pull_from_api():
        ```
        Pull data from API and return in payload format
        ```
        # Handle any logic needed for the external API and
        # return a list of pairs for name of backend API to call and the payload to pass to it.
        return [(endpoint_name1, payload1), (endpoint_name2, payload2)]
```

`BaseIngress` then runs `pull_from_api` and calls the backend with authentication for each output. This gives ingress functions a standard interface, which we can use when wrapping them in Azure functions.
