### ISSUE TITLE
Decide on database constraints to be implemented in code

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/DTBase#11]
Given the structure of our tables and how they relate to one another, it is likely necessary to impose constraints in the python code as opposed to the database itself.   
Here is a list (append / edit as required) of possible constraints we might want:
- [x] No duplicate locations
- [x] No duplicate location schemas
- [x] No duplicate location identifiers
- [x] Locations respect their schemas (have all the necessary identifiers, with the right data types, and no other identifiers)

**Comment by mhauru** [comment]
I've started enforcing the ticked ones in `backend/locations.py` (which in retrospect should probably rather be `core/locations.py`. You can still bypass them by doing raw sequel queries of course.
