### ISSUE TITLE
Add frontend forms for editing and deleting sensors

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/DTBase#112]

**Comment by GiorgioCerro** [comment]
I think this has been closed accidentally.

I am working on this atm.

So far:

- there is an edit button at the end of each row in sensor tables
- when clicking on it a pop up window opens (don't like that it open outside the actual webpage, but I'll work on this later)
- there are three buttons: submit (which should submit the changes), cancel (which closes the window) and delete (which delete the sensor)

To do:

- list the attributes of the selected sensor in the popup window
- create the function in the route.py for submitting the new form for the existing sensor
- create the function in the route.py to delete the sensor

**Comment by mhauru** [comment]
Don't know why I closed this, sorry about that. Let me know if you want advice for the making the routes.

**Comment by mhauru** [comment]
Done, #183
