### ISSUE TITLE
Check python version compatibility

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/DTBase#124]
A Turing researcher was checking our code out, and said that even though pyproject.toml says we support python3.8, some of the dependencies don't. This should be fixed, but more generally we should have a way of checking that we actually support all version we claim to. Probably the best and easiest way would be to modify the unit tests GitHub Action to run on all Python versions we claim to support.

**Comment by EdwinB12** [comment]
Linked to #119

**Comment by EdwinB12** [comment]
fixed by #134
