### ISSUE TITLE
Make the frontend domain settable

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/DTBase#200]
Currently the domain is just whatever random name pulumi happens to generate for the frontend server. It's got an ugly string of random characters in it.

**Comment by GiorgioCerro** [comment]
I've been investigating this the whole day and couldn't get a final conclusion yet. 
At the moment the most trusted theory is that we might need to pay?
On the Azure Portal, when we click on Add Custom Domain, it allows us to choose between AppServiceDomain (which we need to buy for 12 $) or AllOtherServiceDomain, which I still need to understand if I can find some for free?
