### ISSUE TITLE
Create a simple services/model example 

### ISSUE THREAD

**Issue by EdwinB12** [alan-turing-institute/DTBase#212]
Implement some kind of simple model such as a smoothing service and document how it is implemented from end-to-end. 

Include: 

- [ ] Writing of the class
- [ ] How it takes arguments 
- [ ] How it can be run locally 
- [ ] How it can be run on Azure
- [ ] How it can scheduled on Azure
- [ ] Update models readme with this example 
- [ ] Consider writing a notebook in examples for users to use.

**Comment by mhauru** [comment]
A request from @vijja-w: Add a bit at the end of the example about how to turn these into Azure functions. Let's see how detailed we can make that once the PR is otherwise done.
