### ISSUE TITLE
Frontend forms for adding location and sensor information

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/DTBase#32]
See #9 
we should add forms to the skeleton frontend that allow people to add
- [ ] LocationSchema (via adding LocationIdentifiers).
- [ ] Locations
- [ ] SensorTypes
- [ ] SensorMeasures
- [ ] SensorLocations (with time ranges)

**Comment by mhauru** [comment]
See https://github.com/alan-turing-institute/DTBase/issues/9#issuecomment-1792265758
