### ISSUE TITLE
Get Pat's farm setup modeled via DTBase

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/DTBase#35]
Add sensor(s) and location(s) via web frontend, and sensor readings on a regular basis.   Do we want the readings to be added by hitting our API endpoint directly?   Or do we want an Azure function running on a schedule, that interfaces two APIs?

**Comment by mhauru** [comment]
I'm unsure what the status of this is, but given that this has not been discussed in the last 6 months at all, I'm closing for now.
