### ISSUE TITLE
Modify data model, access functions, and API to link ModelRun to sensor/measure

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/DTBase#41]
The current ModelRun class doesn't have any column that indicates the actual measurement to which the predicted values should be compared.
In CROP, we have a "sensor_id" ForeignKey, but the actual variable (temperature) is hard-coded.
Here we can add (nullable) columns for both `sensor_id` and `sensor_measure_id`.

**Comment by mhauru** [comment]
Done
