### ISSUE TITLE
Frontend tests

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/DTBase#42]
Even with a very bare-bones Flask frontend, we should write tests to ensure that expected pages render, as was done for CROP.

**Comment by mhauru** [comment]
Note that this was marked as "in progress" on one of the old boards, should check what the status is.

**Comment by EdwinB12** [comment]
I've been highly recommended cyprus

**Comment by mhauru** [comment]
There are currently already basic tests in place that get the HTML for each of the pages and check that some expected text appears on the page. These mostly rely on mocking responses from the backend. In the PR that implements user management I'll also add tests that talk to an actual backend (ended up implementing that on the way to user management anyway).

This could of course be greatly improved with something that actually checks functionality, javascript, how things render visually, etc., but we could consider a first version of frontend tests done as-is.

**Comment by mhauru** [comment]
The current tests are actually okay. To be improved later, but the first iteration can be closed.
