### ISSUE TITLE
Integration with GrowApp

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/DTBase#43]
GrowApp is the system developed by PurpleCrane to keep track of batches of crops in a farm.
Each batch is assigned a unique ID, and information is recorded about
* What crop is being grown
* How much of it
* Times that it is transferred through the various stages (propagation, growing, harvesting, ...)
* Location in the farm where it grows
* Harvest yield.
* Losses due to disease, defects.

For CROP, we had an ingress function that queried the GrowApp database and transferred the data to the CROP database.
For DTBase, we may want to use an API instead, or potentially even combine the databases.

**Comment by mhauru** [comment]
Unclear if we'll still be using GrowApp, reopen if yes
