### ISSUE TITLE
Configure/create Azure functions via Frontend?

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/DTBase#49]
Very vague idea at this point, but for a general digital twin, with minimal developer input, we may want to somehow have the users control e.g. what predictive model is run on what data and how often.
This would require some way of the frontend webapp being able to create and configure Azure resources (Function Apps).  Not sure if/how this is possible/desirable.

**Comment by mhauru** [comment]
The "run now" aspect of this now exists. The bit that's missing is the scheduling, but that is now covered by #193 and #194, so I'm closing this one.
