### ISSUE TITLE
Pulumi deployment and Dockerfiles

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/DTBase#5]
How much of current CROP infrastructure can we just copy over?

**Comment by mhauru** [comment]
There's now an `infrastructure` folder with a working Pulumi deployment, and a Dockerfile for the backend. Currently that's all we have to deploy anyway, so I'm closing this for now. We should open more issues for doing the infra stuff for function apps and front end once those features are ready to go.
