### ISSUE TITLE
Add Python type annotations

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/DTBase#95]
These could be helpful for code readability and catching some bugs. Especially useful on the front end side, since testing is hard.

**Comment by GiorgioCerro** [comment]
List of al the files:

- [ ] backend
- [ ] core
- [ ] functions
- [ ] ingress
- [ ] models
- [ ] tests
- [ ] webapp

**Comment by GiorgioCerro** [comment]
To double check:

- in dtbase/backend/api/__init__.py: 
     - the func user_loader takes id as input, is it int or str? I went for str
     - shutdown_session, what is exception?

-

**Comment by mhauru** [comment]
> the func user_loader takes id as input, is it int or str? I went for str

An `int`. This can be seen on line 667 of `core/structure.py`, where we set the data type of the relevant PostgreSQL column.

> shutdown_session, what is exception?

Don't know, it's curiously unused. Probably a flask thing, looking at the `app.teardown_request` decorator might answer this. I need to learn how all this flask user management stuff works.

>add_default_session, the only variable I can specify is session, which is a sqlalchemy.orm.Session object

I see, yeah, this is starting to stretch my understanding of the python type annotation system. In other languages I would make `func` be of a parametric type that takes in an arbitrary set of arguments `T` returns something of an arbitrary type `R`, and then make the return value be a function that takes in `T` plus a `Session`, and also returns `R`. Not sure if/how this is can be done in Python, but happy to look into this to learn more.

> check_keys, payload is Dict[str, str] and keys List[str] and api_endpoint str?

Hmmm, maybe. In principle this could handle keys of any type, not just strings, not sure if we use it that way. Another case for type variables, where I would like to make the types be `payload: Mapping[T, Any], keys: Container[T], api_endpoint: str`, with `T` being a free type parameter. `Mapping` and `Container` are more abstract versions of `Dict` and `List`, allowing `keys` to be for instance a set as well as a list. They can be imported from `collections.abc`.

> parse_url_parameter: what is request?

I think that would be a `flask.Request`.

**Comment by GiorgioCerro** [comment]
dtbase/webapp/app/base/routes.py: what is error?

**Comment by mhauru** [comment]
For `error` in `webapp/app/base/routes.py`, I'm a bit unsure, but I think it may just be `Any`. I would have expected something like `flask.Request` though. The function given to the `@blueprint.errorhandler` decorator should be of type `ErrorHandlerCallable`, which seems to take `Any` as its argument, which I find a bit surprising. `@blueprint.route` should be applied a function of type `RouteCallable`, which, even more confusingly, seems to take a variable number of arbitrary arguments. I'm reading these types from [here](https://github.com/pallets/flask/blob/8d9519df093864ff90ca446d4af2dc8facd3c542/src/flask/typing.py#L85). So all in all a bit confused by this!

For `redirect` and `render_template`, these are defined by flask. Their return values seem to be `flask.BaseResponse` (see [here](https://github.com/pallets/flask/blob/8d9519df093864ff90ca446d4af2dc8facd3c542/src/flask/helpers.py#L232)) and `str` (see [here](https://github.com/pallets/flask/blob/8d9519df093864ff90ca446d4af2dc8facd3c542/src/flask/templating.py#L140)), if those are what you need. The above links also show you the arguments.

**Comment by mhauru** [comment]
If you've gotten parts of the codebase done, do you think it would make sense to make a pull request for some of those parts? I'm working on some backend code and could start using the annotations you've made, and we could see if there are any conventions we need to be aligned on.

**Comment by GiorgioCerro** [comment]
Thanks again for all the suggestions!
Yes, I think it makes sense actually. I wanted to finish everything before making a pull request but it's actually taking some time. So most of the code is done, just two folders are missing. I'll make a pull request of what is done already and continue with the rest.
