### ISSUE TITLE
Migrate to pyproject.toml

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/DTBase#99]
Replacing setup.py and requirements.txt. Doesn't necessarily mean using some fancy tool like poetry.

**Comment by EdwinB12** [comment]
I've started looking at this. . Just wrestling with entry points which I've never implemented in pyproject.toml before.

**Comment by mhauru** [comment]
Let's talk tomorrow, I started as well (should have checked here first), can compare notes

**Comment by mhauru** [comment]
Closed by #110
